branch: true
ignore-not-existing: true
llvm: true
filter: covered
output-type: lcov
output-file: ./lcov.info
prefix-dir: /home/user/build/
ignore:
  - "/*"
  - "C:/*"
  - "../*"
  - "./.*"
  - "./*.md"
  - "./*.toml"
  - "./rust-toolchain"
